# Setup
title:               ferdzo's blog
tagline:             'Blog of a CS student for system and network administration, computer hardware and amateur radio'
description:         'Original content from every aspect of our lives '
url:                 https://blog.ferdzo.xyz
baseurl:             ''
paginate:            5
permalink:           pretty
future: true
# About/contact
author:
  name:              Andrej Mickov
  url:               https://twitter.com/f3rdz0
  email:             andrej@ferdzo.xyz

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
