# Setup
title:               ferdzo's blog
tagline:             ''
description:         'Blog for everything '
url:                 https://blog.ferdzo.xyz
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Andrej Mickov
  url:               https://twitter.com/f3rdz0
  email:             andrej@ferdzo.xyz

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
